// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Swaggerの例",
    "version": "1.0.0"
  },
  "host": "localhost",
  "basePath": "/v1",
  "paths": {
    "/user/{user_id}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "userAPI"
        ],
        "summary": "ユーザーIDによって、ユーザー情報を取得する",
        "operationId": "getUserByUserId",
        "parameters": [
          {
            "type": "number",
            "description": "ユーザーID",
            "name": "user_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "成功なレスポンス",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "無効なユーザーID"
          },
          "404": {
            "description": "ユーザーを見つけていません"
          }
        }
      }
    }
  },
  "definitions": {
    "UpdateUserReq": {
      "type": "object",
      "required": [
        "name",
        "email"
      ],
      "properties": {
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Swaggerの例",
    "version": "1.0.0"
  },
  "host": "localhost",
  "basePath": "/v1",
  "paths": {
    "/user/{user_id}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "userAPI"
        ],
        "summary": "ユーザーIDによって、ユーザー情報を取得する",
        "operationId": "getUserByUserId",
        "parameters": [
          {
            "type": "number",
            "description": "ユーザーID",
            "name": "user_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "成功なレスポンス",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "無効なユーザーID"
          },
          "404": {
            "description": "ユーザーを見つけていません"
          }
        }
      }
    }
  },
  "definitions": {
    "UpdateUserReq": {
      "type": "object",
      "required": [
        "name",
        "email"
      ],
      "properties": {
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string"
        }
      }
    }
  }
}`))
}
